DROP TABLE IF EXISTS JENRES;
CREATE TABLE JENRES(
    ID BIGINT
    , Name VARCHAR(255) NOT NULL
    , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGINT
    , Name VARCHAR(255) NOT NULL
    , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID IDENTITY PRIMARY KEY
    , Name VARCHAR(255)
    , AuthorID BIGINT NOT NULL
    , JenreID BIGINT NOT NULL
    , PublishingYear INT
    , FOREIGN KEY (AuthorID) REFERENCES AUTHORS(ID)
    , FOREIGN KEY (JenreID) REFERENCES JENRES(ID)
    );
